[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Data Types"
edition = "2018"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "safe-nd"
readme = "README.md"
repository = "https://github.com/maidsafe/safe-nd"
version = "0.8.0"

[dependencies]
# Ensure bincode version is identical to that in SAFE Client Libs and SAFE Vault.
bincode = "=1.1.4"
ed25519-dalek = "~0.9.1"
hex_fmt = "~0.3.0"
multibase = "~0.6.0"
rand = "~0.6"
crdts = "^2.0.0"
serde = { version = "~1.0.97", features = ["derive"] }
sha3 = "~0.8.2"
threshold_crypto = "~0.3.2"
tiny-keccak = "~1.5.0"
unwrap = "~1.2.1"

[dev-dependencies]
hex = "~0.3.2"
rand_xorshift = "~0.1.1"

[features]
default = [ "ed25519-dalek/serde" ]
