[package]
name = "safe-nd"
description = "Safe Network Data Types"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/maidsafe/safe-nd"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
edition = "2018"

[dependencies]
maidsafe_utilities = "~0.18.0"
rust_sodium = "~0.10.2"
serde = "~1.0.37"
serde_derive = "~1.0.27"
threshold_crypto = "~0.3.1"
routing = { git = "https://github.com/lionel1704/routing", branch = "patch" }
tiny-keccak = "~1.4.2"

[dev-dependencies]
hex = "~0.3.1"
rand = "~0.4.2"
unwrap = "~1.2.0"
